### ISSUE TITLE
how to train the mode on cross dataset as the label scores range from different dataset are different?

### ISSUE THREAD

**Issue by micklexqg** [NeosXu/LoDa#1]
Hi, thanks for your nice work. how to train the mode on cross dataset as the label scores range from different dataset are different?
some values are less than 10, while some are larger than 50.

**Comment by NeosXu** [comment]
Hi, thanks for your attention. Our model has not been trained simultaneously on multiple datasets; all our experiments have been conducted by training and evaluating on a single dataset. 
However, some studies, such as Blind Quality Assessment for in-the-Wild Images via Hierarchical Feature Fusion and Iterative Mixed Database Training, Blind image quality assessment via vision-language correspondence: A multitask learning perspective, etc, have discussed cross-dataset training. If you are interested in cross-dataset training, I recommend you to follow these studies.
