### ISSUE TITLE
Reported performance

### ISSUE THREAD

**Issue by hazelAutumn** [NeosXu/LoDa#3]
Hi,
Thanks for your great work.
I would like to know how did you get the numbers in Table 1. Did you train and test the models (besides LoDa) on all the 7 datasets by your self, or were they reported before in other papers?
With regarding the performance of LoDa, are the reported result calculated by taking the average of results from 10 splits?

I am looking forward to your answer.
Thank you so much.

**Comment by NeosXu** [comment]
1. We directly utilized the results reported in the previous papers.
2. The reported result represents the median of 10 splits, as is customary in most prior papers.

**Comment by hazelAutumn** [comment]
Thank you so much for your prompt response!
